### PR TITLE
Added documentation on how to configure the Swarm Container in an Arquillian test

### PR DESCRIPTION
**Pull request by woelfle**
Added an example on how to configure the Swarm Container in an Arquillian test by implementing the ContainerFactory interface.

### CODE REVIEW

**Comment by kenfinnigan** [comment]
It looks like one commit adds the doc and another removes it, resulting in a net no change.

Is that intended?

**Comment by woelfle** [comment]
Sorry, my fault. The second commit was not intended. This is my first attempt to provide a Pull Request. Looks like I've done something wrong. Is it possible to remove the second commit from the Pull Request or do I have to provide another Pull Request?

**Comment by kenfinnigan** [comment]
No problem, we all had to learn at one point.

Do you want to fix it or we can pick out the commit that has changes?

**Comment by woelfle** [comment]
I'll close the pull request and create another one. I'll have to practice ...

**Pull request closed without merging**
